apiVersion: apps/v1
kind: Deployment
metadata:
  name: adddeploy-deploy1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: add
  template:
    metadata:
      labels:
        app: add
    spec:
      containers:
      - name: addct
        image: devopsinsiders/micro-addtask
        ports:
        - containerPort: 8000
        # Uncomment and update the env variable if needed
        # env:
        # - name: CONNECTION_STRING
        #   value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:sahildbserver1234.database.windows.net,1433;Database=sahildb;Uid=Badbunny;Pwd=Karolg@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30"

---
apiVersion: v1
kind: Service
metadata:
  name: add-svc1
spec:
  selector:
    app: add
  ports:
    - port: 80        # External port exposed by the service
      targetPort: 8000 # Port your container is listening on
  type: LoadBalancer   # Change to ClusterIP (default) or NodePort if required
